export const categories = ["Notebooks",
  "Pens",
  "Pencils",
  "Markers",
  "Highlighters",
  "Erasers",
  "Sharpeners",
  "Rulers",
  "Staplers",
  "Paper Clips",
  "Sticky Notes",
  "Folders",
  "Binders",
  "Scissors",
  "Glue",
  "Tapes",] as const;